### ISSUE TITLE
LibreOffice floating windows renders system unresponsive

### ISSUE THREAD

**Issue by lvella** [xmonad/xmonad#11]
I was trying to work with LibreOffice Calc charts when it stroke me. Whenever I opened a floating dialog (for changing chart properties and data range), there was high probability of the system stopping to react to input. Sometimes I had trouble clicking the OK button, but eventually it made the entire system unresponsive, and I couldn't even switch workspaces. So I had to switch to another vterm and kill LibreOffice.

Should be easy to reproduce: try drawing some charts, then edit it by opening and using the dialogs.

**Comment by davama** [comment]
Something similar happens to me while using LibreOffice. At first i thought it was my updatepointer but even without i still have same issue.

**Comment by geekosaur** [comment]
LibreOffice (and other StarOffice/OpenOffice derivatives) do this if you don't have EwmhDesktops configured. Arguably it is a bug in those programs since it should be checking _NET_SUPPORTED and either falling back to compatible behavior or, if EWMH is absolutely necessary for some reason, throwing an error.
