### ISSUE TITLE
Rebuild if existing executable does not start

### ISSUE THREAD

**Issue by nomeata** [xmonad/xmonad#14]
This is forwarded from http://bugs.debian.org/808422

It may be that after a system upgrade, the compiled xmonad binary does not work any more, due to missing shared libraries. A simple recompilation would amend the problem, and not lock out the user. It would be nice if the `xmonad` wrapper binary would try that if starting the `xmonad` binary fails very quickly. Probably needs a few heuristics, but would be very useful.

**Comment by pjones** [comment]
I'd like to see this implemented as part of Issue #8.

**Comment by pjones** [comment]
I've been thinking, this is really due to your system setup and the way you build and manage XMonad.  I recommend compiling/installing XMonad as part of your system upgrade.  If that's not possible you should switch to NixOS.  Just kidding ;)

I recommend you use the new features in XMonad 0.13 to detect this situation and rebuild your own XMonad before starting it.  If you come up with something nice that you think everyone could use please send a PR.

The new features I'm referring to will be documented shortly.  See the `CHANGES.md` and source code until I get that docs update.  Specifically, you can now have a build script in `~/.xmonad/build` that you could call before starting XMonad.

**Comment by dddoss** [comment]
I just ran into this issue and had a somewhat frustrating time debugging it. I acknowledge it is somewhat due to the setup of individual systems and there are workarounds, but it seems like it'd be relatively easy to fix--maybe the compiled binary includes the xmonad version used to compile it in metadata, and if there is a mismatch between the installed and compiled versions, the wrapper binary triggers a recompile? Maybe there's reasons this is a bad idea, but I'm not seeing them.

**Comment by mgsloan** [comment]
May also be good to invoke a fallback WM, but noidea how to do that generically.
