### ISSUE TITLE
dzen2 gets overlapped

### ISSUE THREAD

**Issue by su8** [xmonad/xmonad#143]
Workspaces, status bar gets overlapped

![](https://cdn.pbrd.co/images/GMNU3SS.png)

**Comment by geekosaur** [comment]
If you're using xmonad 0.12 or later, you need `docksEventHook` and `docksStartupHook`. Starting with xmonad 0.13, the `docks` combinator is strongly recommended instead.

dzen2 also requires the `-dock` option (this is a bug on our side but we still haven't tracked it down; the code to handle it without `-dock` exists but somehow isn't doing anything).

**Comment by su8** [comment]
Thank you geekosaur, but I think to roll back to 0.12.

**Comment by geekosaur** [comment]
You should be aware that the strut code in 0.12 is severely buggy and it's unlikely that you will be able to get docks to behave properly.

**Comment by geekosaur** [comment]
I should also mention that most weird behavior in 0.13 is related to the state file bug; just remove `~/.xmonad/xmonad.state` before running xmonad (it should only exist during a mod-q restart... which means you can't remove it in your `xmonad.hs` without breaking that; do it in the session setup instead). (This has been fixed in git.)
