### ISSUE TITLE
Firefox doesn't resize on launch.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#144]
### Problem Description

The issue has been present for years on https://bugzilla.mozilla.org/show_bug.cgi?id=686747.

Firefox remembers its last window size and restores it on restart, but it doesn't adapt to the new window size until it is resized manually.

Can it be fixed or worked around in xmonad?

**Comment by geekosaur** [comment]
That bug references other tiling window managers, specifically i3wm.

Window managers do not draw windows; the application must handle the events the X server sends it in response to its window being mapped. If it's not redrawing itself to fit the window it got, this is Firefox's bug (or possibly Gtk's, but other Gtk programs don;t have this problem so that is unlikely). Most likely is Firefox is not paying attention to the actual window size it got; we can't fix that for them.

**Comment by geekosaur** [comment]
My guess BTW is that they assume that all window managers use `ConfigureRequest`. But tiling window managers don't (relying on an edge case in ICCCM for backward compatibility), because another window could be opened and change the tiling between `ConfigureRequest`/`ConfigureNotify` and `MapWindow`; tiling can only be done after the window is actually mapped. So they are probably only checking for a different window size in a code path that tiling window managers can't use.

**Comment by crocket** [comment]
Is there a workaround for this? Weirdly, tor browser doesn't have an issue with xmonad although it is derived from firefox. Perhaps, I should find a firefox derivative?

**Comment by geekosaur** [comment]
Nothing that can be done in xmonad, except something really horrid like a `handleEventHook` triggered by the next event received after it is handled in the `manageHook` (this requires something to detect a Firefox window in the `manageHook` and set a flag + its window ID in XS, then the `handleEventHook` looks for that flag being set, grabs the window ID, and clears the flag) that forcibly resizes the window and immediately resizes it back to its original size --- and hope Firefox responds correctly to the resize events.
