### ISSUE TITLE
GUI applications "Hiding" after switching workspaces

### ISSUE THREAD

**Issue by CategoryQ** [xmonad/xmonad#145]
### Problem Description

Some applications are "hiding" after switching workspaces. So far I have experienced this when trying to run Liferea (RSS feed reader) and HexChat (IRC client).

Application is launched with mod-P, and is visible on the workspace. If I use mod-Number to change to a different workspace, then back to the workspace where Liferea  or HexChat were launched, the windows are no longer visible.

ps -A still shows the proccesses as running, but the window is no longer drawn anywhere

Launching the apps from a terminal show nothing out of the ordinary in their errors

This behaviour is the same if the offending window is alone on a workspace, tiled with other apps, or a floating window.

### Configuration File

I have completely stripped my config file back to absolute basics, and changing the terminal to xterm made no difference:-

import XMonad

main = do
	xmonad defaultConfig
		{ terminal = "terminator"
		}

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

Happy to upload any logs to assist, would be great to find a fix for these last 2 programs in my workflow

**Comment by geekosaur** [comment]
It seems both hexchat and liferea can minimize to an icon in a systray applet. Gtk's implementation of this is buggy and can become "stuck", which shows these symptoms --- and it can be reproduced in window managers other than Gtk (in fact, when I went looking to see if liferea had such an icon, there's an indirect reference to this bug in liferea's own FAQ: it's getting into this state despite the environment not having a systray to show the app icon in).

Unfortunately, the workaround in all known cases is to remove the application's config file, since when Gtk gets into this state you can no longer minimize/restore it from the systray (this causes the window to appear and immediately vanish again) and it will randomly display or not. For hexchat it may be sufficient to edit `~/.config/hexchat/hexchat.conf` and remove all of the `gui_tray_*` options. I don't know what minimal config change might work for liferea; hopefully it stores the feed information somewhere other than the main config file.

You might want to verify this issue in another window manager before nuking config files: once it shows up, it should occur in any window manager, not just xmonad.

**Comment by CategoryQ** [comment]
That completely solved the issue, thanks!

**Comment by liskin** [comment]
liferea's support for tray icon can be turned off in Settings -> Plugins. Maybe that can help prevent this from happening ever again?
