### ISSUE TITLE
windows in the first workspace overlap xmobar

### ISSUE THREAD

**Issue by QiBaobin** [xmonad/xmonad#147]
### Problem Description

Start applications on the first workspace, their windows overlap the area of status bar. Other workspaces work well, and hide/show status bar again fixes the issue.

### Configuration File

```haskell
import XMonad.Util.EZConfig
import XMonad.Hooks.DynamicLog
import XMonad.Prompt
import XMonad.Prompt.Window
import XMonad.Prompt.RunOrRaise
import XMonad.Prompt.Shell

import XMonad.Actions.Warp

main = xmonad =<< xmobar myConfig

myConfig = def { modMask = mod4Mask
               , focusFollowsMouse  = False
               , terminal = "urxvtc"
               } `additionalKeysP` myKeys

```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
You aren't using `XMonad.Hooks.ManageDocks` so there is no checking for status bars at all.

**Comment by QiBaobin** [comment]
Based on https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Hooks-DynamicLog.html, is it enough to just use DynamicLog?

**Comment by geekosaur** [comment]
It is not; it installs the layout portion but not the `manageHook` or the other necessary hooks. In fact, it is arguably a bug that it does that, considering that from xmonad 0.12 on, you need a number of extra hooks for status bars to work properly; `avoidStruts` relies on information from the `manageHook`, `handleEventHook`, and `startupHook` to even know that docks are present. (It basically worked before only because it scanned every window whenever it ran the layout, looking for dock windows. This doesn't scale; `XQueryTree` is fairly expensive.)

The correct fix for all of this is to merge `EwmhDesktops` and `ManageDocks` into core xmonad and make them part of the default layout, as they are expected to work 'out of the box' these days (core xmonad only promises ICCCM support, not EWMH). There's already a ticket for it (#95).

**Comment by QiBaobin** [comment]
Thanks @geekosaur
