### ISSUE TITLE
Configuring border position

### ISSUE THREAD

**Issue by Avaq** [xmonad/xmonad#152]
### Problem Description

Some weeks ago I asked [a question on Stack Exchange](https://unix.stackexchange.com/questions/413095/rendering-window-border-on-a-specific-side-in-xmonad) which [earned me the Tumbleweed badge](https://unix.stackexchange.com/help/badges/21/tumbleweed?userid=169543). The question in question questioned the lack of being able to configure *border position* in XMonad.

I would really like to be able to configure border position as well as colour, in a similar fashion to how this is possible in XMobar by specifying `Config { border = BottomB }`, for example.

I hope I've opened this issue in the right place. I'm not sure where else to go. There's `XMonad.Layout.NoBorders` in contrib, but this extension seems to focus mainly on *when* to show the borders, and not *where*.

Is this impossible and should I give up?
Is this already possible and have I been missing it?
Can I submit this as a feature request?

**Comment by LSLeary** [comment]
The problem with this is that xmonad doesn't draw its own borders; it just tells X how thick they should be and what colour. I believe it's also possible to tell X to use certain patterns like dotted/stippled rather than a complete line, but I don't think you can tell it what side of the window gets border.

To get this result in xmonad, you'd need to have width 0 borders and then implement window decorations placing a coloured bar where you want the 'border'. I don't know anything about window decorations myself, but there are xmonad-contrib modules which implement them, so you can look to those for reference.

**Comment by Avaq** [comment]
Thank you for your reply. I have a much better understanding of the problem now!

> I don't think you can tell [X11] what side of the window gets border

From what I can find out after some searching, it does indeed seem like X11 cannot: https://www.commandlinux.com/man-page/man3/XCreateWindow.3.html

> I believe it's also possible to tell X to use certain patterns like dotted/stippled

I couldn't find evidence of this either though, so perhaps I missed something.

> you'd need to have width 0 borders and then implement window decorations 

Clear. Everything points to this issue being out of scope from XMonad. I'll close it.

> there are xmonad-contrib modules which implement [window decorations], so you can look to those for reference

Thanks again. I will!

**Comment by geekosaur** [comment]
It's the `border_pixmap` element in the `XSetWindowAttributes` structure. https://tronche.com/gui/x/xlib/window/attributes/border.html

**Comment by Avaq** [comment]
So in theory one could set a bottom-only border by specifying a very large pixmap that wraps around the whole window?

**Comment by geekosaur** [comment]
If you assume all the caveats in the page I linked aren't actually there or don't mean anything, then you might conclude that.

Historically, what you would get is it would use a (borderWidth x borderWidth @ (0,0) section of the pixmap, tiled over the whole border area. Which is also permitted by those caveats.

**Comment by geekosaur** [comment]
Also, the graphics driver writers constantly break server-side borders, because only xmonad and dwm use them these days. And neither uses borderPixmap, so there's probably lots of bugs hidden there.

**Comment by LSLeary** [comment]
I got interested and ended up playing around with XMonad.Layout.Decoration. It's actually pretty easy to write an instance of the DecorationStyle class that will place a border-like decoration on one side of the window. If that side is the top or the bottom then the bar will be wide enough and the window's title text will be rendered in it, but that can be made a non-issue by setting text to the same colour as the bar or supplying an empty font.

I'm using it on the left. Looks pretty good.![:D](https://i.imgur.com/ZntaF6f.png)

```haskell
{-# LANGUAGE MultiParamTypeClasses, FlexibleInstances #-}

import qualified XMonad.StackSet as W
import XMonad.Layout.Decoration
import XMonad.Util.Types

data SideDecoration a = SideDecoration Direction2D
  deriving (Show, Read)

instance Eq a => DecorationStyle SideDecoration a where

  shrink b (Rectangle _ _ dw dh) (Rectangle x y w h)
    | SideDecoration U <- b = Rectangle x (y + fi dh) w (h - dh)
    | SideDecoration R <- b = Rectangle x y (w - dw) h
    | SideDecoration D <- b = Rectangle x y w (h - dh)
    | SideDecoration L <- b = Rectangle (x + fi dw) y (w - dw) h

  pureDecoration b dw dh _ st _ (win, Rectangle x y w h)
    | win `elem` W.integrate st && dw < w && dh < h = Just $ case b of
      SideDecoration U -> Rectangle x y w dh
      SideDecoration R -> Rectangle (x + fi (w - dw)) y dw h
      SideDecoration D -> Rectangle x (y + fi (h - dh)) w dh
      SideDecoration L -> Rectangle x y dw h
    | otherwise = Nothing
```

Don't know if it merits a contrib PR.

**Comment by michaelcurry** [comment]
@LSLeary: I am new to xmonad and Haskell... I really like the implementation you have made above, but I am not sure where to put this code to make it work.  Any pointers in the right direction would be great.

Thanks

**Comment by LSLeary** [comment]
@michaelcurry

I'm going to walk you through how I would figure out how to use this if I'd never seen it before.

The code above declares a new data type, then declares it an instance of an imported typeclass `DecorationStyle`. You can look at the imports and guess which module provides it, or search the xmonad & xmonad-contrib docs for it. Either way you should arrive at: http://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Layout-Decoration.html

Helpfully, the core of the module's interface is at the head of the module:

> ```haskell
> decoration
>   :: (DecorationStyle ds a, Shrinker s)
>   => s -> Theme -> ds a -> l a -> ModifiedLayout (Decoration ds s) l a
> ```
>
> A layout modifier that, with a Shrinker, a Theme, a DecorationStyle, and a layout, will decorate this layout according to the decoration style provided.
>
> For some usage examples see XMonad.Layout.DecorationMadness.

You can see from its type that this gives you a way to use a `SideDecoration`: it accepts for its third argument anything of type `ds a` such that we have a `DecorationStyle ds a` instance. Hence you can use e.g. `SideDecoration L`, so long as the value and its instance are in scope.

But first it wants something of type `s` with a `Shrinker s` instance. What does that mean? You probably don't care, and neither do I. But if you check out the usage examples it mentions by following the link to the `DecorationMadness` module and looking over the source, you'll see they all use the `shrinkText` value.

Next it wants a `Theme`. The documentation for the data type is right there just below `decoration`; it's a straightforward record type with descriptive field names. You can just use `defaultTheme` (or the `def` value it's deprecated in favour of) if you don't care what's in it, but you probably do want to override a few things. So maybe you want to declare and use e.g.:
```haskell
myTheme :: Theme
myTheme = defaultTheme
  { activeColour = "#ffffff"
  , inactiveColor = "#000000"
  , decoWidth = 20
  }
```

Putting it together, we can now declare
```haskell
myDecorate :: l a -> ModifiedLayout (Decoration SideDecoration DefaultShrinker) l a
myDecorate = decoration shrinkText myTheme (SideDecoration L)
```
This is a function that you can apply to your layout in order to decorate it.

But first we need to bring `SideDecoration` into scope, as I mentioned earlier. There are two ways to do this.

The simpler way is just to copy the source code above into your `xmonad.hs` piece by piece. Put the `LANGUAGE` pragma at the top of the file, the imports with the other imports, and the top-level data and instance declarations anywhere below. 

The cleaner way is to put the source code above in a file called e.g. `SideDecorations.hs` in the `~/.xmonad/lib/` directory, and give it a corresponding module header between the `LANGUAGE` pragmas and imports
```haskell
{-# LANGUAGE [...] #-}

module SideDecorations where

import [...]
```

Then in your `xmonad.hs` you can import the module:
```haskell
import SideDecorations
```

**Comment by michaelcurry** [comment]
@LSLeary Thanks for taking the time to explain the above.  I unfortunately am still having issues :-/ I chalk it up to being new to Haskell..  I will keep working on this, but if you get a chance, any ideas/directions would be great.

THANKS,
-- Mike

1. I am getting a compilation error (posted balow)
2. I have added my Files to Gists so you can see the full scope
3. Once myDecorate is not throwing an exception, I am not sure how to get it into the Layout Hook ... if that is where it goes...


Files Gist: https://gist.github.com/michaelcurry/19e2596c52b50a4dfb2c4467776ddcda

Compile Error: 
```
xmonad.hs:223:14: error:
    * No instance for (Eq a) arising from a use of `decoration'
      Possible fix:
        add (Eq a) to the context of
          the type signature for:
            myDecorate :: forall (l :: * -> *) a.
                          l a
                          -> ModifiedLayout (Decoration SideDecoration DefaultShrinker) l a
    * In the expression:
        decoration shrinkText myTheme (SideDecoration L)
      In an equation for `myDecorate':
          myDecorate = decoration shrinkText myTheme (SideDecoration L)
    |
223 | myDecorate = decoration shrinkText myTheme (SideDecoration L)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by LSLeary** [comment]
@michaelcurry 
I gave `myDecorate` the type signature that it _should_ have, but unfortunately the `X.L.Decoration` module is misusing constraints by imposing them on the `decoration` function that constructs a layout, rather than just on the `LayoutClass`/`LayoutModifier` instance that actually uses them. This misuse then flows down to you, requiring you to reassert the constraint.

In short, as the compilation error quite helpfully instructs, you need to add an `Eq a` constraint to the type signature of `myDecorate`:
```haskell
myDecorate :: Eq a => l a -> ModifiedLayout (Decoration SideDecoration DefaultShrinker) l a
```
Re:
> I am not sure how to get it into the Layout Hook ... if that is where it goes...

yes, as I originally said:
> This is a function that you can apply to your layout in order to decorate it.

Your layout is currently:
```haskell
myLayout = avoidStruts (tiled ||| Mirror tiled ||| Full)
```
That is the function `avoidStruts` applied to what I'll call the "cyclic combination" of the layouts `tiled`, `Mirror tiled` and `Full`. You can e.g. apply `myDecorate` to your whole layout:
```haskell
myLayout = myDecorate (avoidStruts (tiled ||| Mirror tiled ||| Full))
```
Or just to one or two of the layouts in the cyclic combination:
```haskell
myLayout = avoidStruts (myDecorate tiled ||| myDecorate (Mirror tiled) ||| Full)
```

**Comment by tim-hilt** [comment]
Does this still work for you? I would really love to have Borders just on one side of the window, but as the OP (when submitting the issue), i'm pretty new to Haskell and not able to come up with a working solution.

I got as far, as to having no compiliation-errors by working through the comments and gists on this page. However, when i restart XMonad, my whole layout get's into `Full` and no border is displayed. Could this be due to changes in the XMonad-source-code?

**Comment by Avaq** [comment]
@tim-hilt This still works for me. I've posted my whole configuration for you. Here's the relevant sections:

- The suggestion from https://github.com/xmonad/xmonad/issues/152#issuecomment-362716434: https://gist.github.com/Avaq/9691fa3f8b6538fb949570884e5ee91e#file-xmonad-hs-L96-L112
- It being used in a custom layout composition: https://gist.github.com/Avaq/9691fa3f8b6538fb949570884e5ee91e#file-xmonad-hs-L121-L122
- The theme I'm using for said layout. Note that I'm using a 1px border size. I really just wanted the smallest possible separator between windows. I find that a 1px border on the bottom works best: https://gist.github.com/Avaq/9691fa3f8b6538fb949570884e5ee91e#file-xmonad-hs-L70-L81
- The custom layout being configured in the settings: https://gist.github.com/Avaq/9691fa3f8b6538fb949570884e5ee91e#file-xmonad-hs-L148

<details><summary>Screenshot</summary>

Here's a screenshot of what my "dev" workspace looks like. You'll see 4 windows, each with a subtle 1px line at the bottom (you may need to view the image at original size to see it properly). The focused window (Sublime, as indicated in the XMobar) has a line with a slightly higher contrast.

![latest-screenshot](https://user-images.githubusercontent.com/1217745/101468003-5feea700-3943-11eb-9d9b-2913c342b9ad.png)

</details>

**Comment by tim-hilt** [comment]
Let's discuss this in the comments on your gist, as the issue itself is considered to be solved. As i stated before: I might have these problems, because of me newb-ness in Haskell. Thanks for the reply!
