### ISSUE TITLE
Window spawns on monitor focused at the time loading finishes.

### ISSUE THREAD

**Issue by Gab0** [xmonad/xmonad#158]
Let's say I'm working on two monitors.
I press a hotkey defined at xmonad.hs to spawn some application while focus is on left monitor , because I what the app to spawn on the left screen.
While the program starts, I move the focus to the right monitor to keep working. That app will finish loading and spawn on the right monitor.
So, theres a function/library to pin a spawning window to the original monitor it was set to spawn in?

That is the standard behavior on any xmonad.hs configured for multiple monitors.

Thanks!

**Comment by geekosaur** [comment]
Not 100% reliably, nor can there be: an application has no idea where it spawned, because details of the window system are not wired into the kernel and propagated to child processes. If the application supports EWMH `_NET_WM_PID` and doesn't use a "factory" configuration, then `XMonad.Actions.SpawnOn` can usually fake it, though. See https://wiki.haskell.org/Xmonad/General_xmonad.hs_config_tips#Terminal_emulator_factories.

**Comment by Gab0** [comment]
spawnHere does exactly what was needed ;) 
Worked with every program tested. cheers!
