### ISSUE TITLE
add key use multi KeySyms

### ISSUE THREAD

**Issue by findNextStep** [xmonad/xmonad#160]
### Problem Description

I`m config my own xmonad.
When I wish to bind different function on left alt and right alt I found there seem to no way.
-- My English is very poor, please don't mind 

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
xmonad depends on the keyboard mapping for this. You'll want to use Xkb or xmodmap to assign different keysyms to each of the keys.

Often this is done already, but you'll need to use keysym bindings (`additionalKeys`) instead of strings (`additionalKeysP`); unless you're using something like VNC that doesn't do this for you. For example, standard xorg should have separate `Alt_L` and `Alt_R` keysyms; check `xmodmap -pm` to verify. These would be `xK_Alt_L` and `xK_Alt_R` in xmonad.

If you need to adjust these, you would normally select a more appropriate Xkb keyboard. `xmodmap` is deprecated and can confuse (or be confused by) complex Xkb configurations, but you could try using it to change the keysym associated with either key's keycode (`xmodmap -pk` or `xmodmap -pke` for list) and adjust the modifier mappings (`xmodmap -pm` for list) to match so programs expecting alt keys (`mod1` on PCs) see what they expect.

**Comment by findNextStep** [comment]
emmmm
What I want is that for example ,I want to use left_alt and f4 bind to kill(but do nothing or others when I use right_alt and f4) but the keyMask can`t satisfy what I need

**Comment by geekosaur** [comment]
You have to bind the two keys to different modifier masks. I have right alt bound to `mod5`, but that is also defined as the compose modifier as I have xorg configured; you may have to use `mod3` instead.

**Comment by findNextStep** [comment]
@geekosaur I know your means! It work! thanks a lot
