### ISSUE TITLE
~/.xmonad folder being created with configuration in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by pjan** [xmonad/xmonad#164]
### Problem Description

The xmonad.hs configuration is put in the xmonad folder within `XDG_CONFIG_HOME` (`~/.config/xmonad`), no `~/.xmonad` folder exists. Recompilation works correctly, but upon finishing a `~/.xmonad` folder exists, breaking a next recompile if the `.xmonad` is not being removed.

I was able to resolve this, by manually creating the xmonad folder in the `XDG_DATA_HOME` one.

The fact that all xmonad folders in each of the XDG ones needed to be created was not obvious from the documentation (changelog). I don't know whether this is expected or not, so not sure what the action points are (if any). I would definitely suggest making this more obvious in the documentation, and maybe also have xmonad create those when the `~/.xmonad` folder doesn't exist, and the configuration file is detected in the `XDG_CONFIG_HOME/xmonad` folder (?)

pinging @geekosaur as I discussed my observation (without finding the cause at that point) on `#xmonad`

**Comment by colonelpanic8** [comment]
Is there any movement on this issue? This can be pretty annoying.

**Comment by mgsloan** [comment]
I think I encountered this too, so I dug into it a bit.  Here are the 3 functions for figuring out the config dir / cache dir / data dir - https://github.com/xmonad/xmonad/blob/master/src/XMonad/Core.hs#L459

Indeed, it looks like the order of resolution for, say, config is `$XMONAD_CONFIG_DIR` then `~/.xmonad`, then `$XDG_CONFIG_HOME/xmonad`.  If none of these exist then either `$XMONAD_CONFIG_DIR` or `~/.xmonad` are created.

To me, it doesn't make much sense to decouple the logic for these three paths.  It should be consistently using `.xmonad` for all 3, or the `XMONAD_*_DIR` vars for all 3, or XDG vars for all 3.  The less invasive change to implement this would be to have one function that yields all 3, and implement the others in terms of that.  The more invasive change would be to figure this out on startup and store it in a ReaderT

**Comment by mgsloan** [comment]
What do y'all think the behavior should be?  Perhaps:

1. If any of the `XMONAD_*_DIR` env vars are set, require all of them be set?
2. If none of those are set, check if any of the XDG dirs exist.  If they are, then only use xdg dirs.
3. Otherwise fallback on `getAppUserDataDirectory "xmonad"`, aka `~/.xmonad`

**Comment by colonelpanic8** [comment]
@mgsloan Yes, I actually just looked and determined the same thing, before I came back here and saw your comment.

To summarize, the non-existence of any of the XDG dirs will result in the creation of a .xmonad dir, which will result in that directory being chosen for all 3, because ~/.xmonad takes precedence over XDG.

> If none of those are set, check if any of the XDG dirs exist. If they are, then only use xdg dirs.

This sort of seems like a problem. I suspect that it could be surprising that when the DATA directory exists for a user, xmonad won't look in ~/.xmonad. It is, admittedly, unlikely that the data directory would exist if the user wasn't using XDG_CONFIG_HOME for the xmonad config as well, but I still think it makes sense to avoid this sort of surprising behavior.

> If any of the XMONAD_*_DIR env vars are set, require all of them be set?

I don't think this one is going to be as much of an issue. If someone knows about these env vars, they are likely to be aware of the significance of each and have enough understanding that they probably won't be confounded by the default behavior.

-----

I could get onboard with what @mgsloan has proposed, but I also think that the problem could be solved  by moving by looking for specific files/directories that xmonad is looking for instead of just checking for the existence of the directory. i.e. look for xmonad.hs or lib or build.

**Comment by mgsloan** [comment]
Makes sense!  Whatever behavior is chosen, ideally xmonad would explain what it is using on startup, and why, by logging to stdout.

**Comment by geekosaur** [comment]
fwiw I did recommend at one point looking for xmonad.hs specifically. But ~/.xmonad should still be fallback/default because that's where a lot of existing configs live, and falling into XDG-style paths just because there's other XDG stuff around will break existing configs.

Ideally this would even allow for hybrids: xmonad.hs in ~/.xmonad but other data via XDG, and such. But that would be much harder to arrange while retaining backward compatibility.

**Comment by colonelpanic8** [comment]
Another thing to note is that because each of the XDG dirs are in different places (at least by default), this problem would not occur if XDG took precedene over ~/.xmonad (which I think it should anyway) e.g. 

if `$HOME/.local/share/xmonad/` (the default XDG_DATA_DIR) exists, we would still properly fall back to `$HOME/.xmonad` as the config directory if `$HOME/.config/xmonad` didn't exist.

It seems that this was the behavior until 2baab2860200ce741090058b3c0b039a2f04e89b
@pjones What was the reasoning for making that change?

**Comment by pjones** [comment]
@IvanMalison The change I made was requested in #71.

**Comment by colonelpanic8** [comment]
> fwiw I did recommend at one point looking for xmonad.hs specifically. But ~/.xmonad should still be fallback/default because that's where a lot of existing configs live, and falling into XDG-style paths just because there's other XDG stuff around will break existing configs.

@geekosaur 
I don't think any one is suggesting this. It's also NOT what the current code would do, even if priority were switched. We would look specifically for the xmonad directories in the XDG directories. There is no way these would show up unless the user has no ~/.xmonad or they manually create them.

I will say that as I mentioned above, I agree with the following sentiment:

```
23:18:51 < dmwit> Perhaps looking for a directory rather than a file is not such great behavior.
23:19:02 < geekosaur> probably it should not just check for the directory, but for xmonad.hs in it
```

Seems like this might do away with a lot of the pain that this issue seems to be causing.
