### ISSUE TITLE
helpCommand does not have newlines

### ISSUE THREAD

**Issue by Emiluren** [xmonad/xmonad#175]
### Problem Description

I just found out about the helpCommand bound to mod-shift-/ but the xmessage window that comes up shows all text on a single line and does not interpret \n as a newline but as the literal characters.

`The default modifier key is 'alt'. Default keybindings:\n\n-- launching and killing programs\nmod-Shift-Enter  Launch xterminal\nmod-p`

after looking at the man page for echo I saw that it needs an -e flag.

So shouldn't [this]([https://github.com/xmonad/xmonad/blob/ecf1a0ca0d094c76a18c2c1b77ac7c1dcac10f5e/src/XMonad/Config.hs#L242](url))

```
helpCommand :: X ()
helpCommand = spawn ("echo " ++ show help ++ " | xmessage -file -")
```

be changed to this?

```
helpCommand :: X ()
helpCommand = spawn ("echo -e " ++ show help ++ " | xmessage -file -")
```

### Configuration File

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
The real problem is that "echo" doesn't behave particularly reliably, where escapes are concerned; see https://everything2.com/title/The+UNIX+and+the+Echo which is a storified version of an actual conflict in "echo" behavior between different systems. (In particular, autoconf-generated configure scripts have a rather horrific amount of goop in them whose sole purpose is to figure out how the local "echo" behaves in that regard, and how to try to make it behave as autoconf expects.)

We should probably figure out a better way to do that, probably by forking a thread to write to xmessage instead of relying on a particular behavior of "echo".

**Comment by Emiluren** [comment]
Ah, I see. Thank you for the explanation

**Comment by slotThe** [comment]
Should've been fixed by https://github.com/xmonad/xmonad/pull/309
