### ISSUE TITLE
ToggleStructs issue after restart xmonad(v0.12)

### ISSUE THREAD

**Issue by jiajunhuang** [xmonad/xmonad#18]
here is my configuration: https://github.com/jiajunhuang/dotxmonad/blob/master/xmonad.hs

when I recompile and restart xmonad, or reboot system, or exit xmonad and login again, the xmobar
will be blocked by other software(e.g. gnome-terminal if you spawn it), so I have to press `mod-b(my mapping for ToggleStructs)` twice, to set xmobar visiable.

**Comment by f1u77y** [comment]
add `docksEventHook` to your `handleEventHook`

**Comment by jiajunhuang** [comment]
solved. thanks.

**Comment by chrissound** [comment]
@f1u77y

Can you explain where one would add those functions to a vanilla xmonad config?

**Comment by geekosaur** [comment]
* `manageDocks` in the `manageHook`
* `avoidStruts` in the `layoutHook`
* `docksEventHook` in the `handleEventHook`
* `docksStartupHook` in the `startupHook`

Or base your config on `desktopConfig` (http://hackage.haskell.org/package/xmonad-contrib-0.12/docs/XMonad-Config-Desktop.html) instead of `defaultConfig` --- and *please* don't use that hideous "example config" that defines everything itself, or you make this difficult to integrate and almost impossible to maintain across versions. Note that, while `desktopConfig` handles most of this for you, you will still need to explicitly use its `desktopLayoutModifiers` if you customize the layouts: it can't sanely insert that itself (and sometimes you wouldn't want it to; you wouldn't be able to define a full-screen layout if you needed it).
