### ISSUE TITLE
Browser briefly displays empty page in XMonad

### ISSUE THREAD

**Issue by brianbuccola** [xmonad/xmonad#187]
### Problem Description

This is a pretty niche issue (originally reported [here](https://github.com/qutebrowser/qutebrowser/issues/4033)), but hopefully someone can help me out. I recently switched (back) to XMonad from dwm, and I noticed immediately that when I switch to a workspace containing Qutebrowser (or switch to the Qutebrowser window from a window in another XMonad tab), I very quickly see a blank webpage (all white). See the example gif [here](https://media.giphy.com/media/fWfDbo6FQ1mmGYZNRv/giphy.gif). It's like a very bright flash of light.

A couple notes:

- If, in Qutebrowser, I change `colors.webpage.bg` from `white` to any other color, then that is the color I see. [Here's another gif](https://media.giphy.com/media/fnJQNoo6KDTw79ksC7/giphy.gif) with the background set to `red`, which makes it much more obvious/severe.
- The issue also happens with other Qt-based browsers, like Falkon, but not with Firefox or Chromium.
- The issue does *not* happen with dwm, herbstluftwm, etc. -- only with XMonad. Compare the above gif (XMonad) with [another gif](https://media.giphy.com/media/1AdZe0Ten4FG4xozRt/giphy.gif) in dwm.

Any idea what could possibly going on?

For now, I'm doing `set colors.webpage.bg black`, which sort of alleviates the problem, but then many webpages get rendered incorrectly because they're meant to be viewed with a white background.

### Configuration File

I was able to reproduce the problem using the minimal configuration file:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
xmonad-testing is not a custom version of xmonad, it is a test framework used with xmonad.

**Comment by brianbuccola** [comment]
Sorry, I didn't realize that. I've just reproduced the problem with xmonad-testing.

**Comment by chrissound** [comment]
Have you tried running a compositer like compiz or xcompmgr (just to see if it makes a difference)? Which graphics card / drivers do you use?

**Comment by geekosaur** [comment]
Also, if I had to guess, it's because xmonad is more minimal and faster than most other window managers, and you're seeing the brief interval between the window being mapped with its default background and the browser responding to the subsequent Expose event and repainting the contents. It's possible that either a compositor or enabling backing store (in effect, retaining the contents of an unmapped window instead of relying on the app to repaint) in the server will help; but xorg has historically had bugs in its backing store implementation.

With respect to firefox and chromium, it'd be interesting to see whether enabling or disabling GPU support changes the behavior; this might indicate instead something about OpenGL configuration.

**Comment by geekosaur** [comment]
(I didn't suggest that the first time because dwm at least used to be as minimal as xmonad. But I think it's less so these days. In particular, reparenting in order to support Java and Mono canvases out of the box would change the timing such that it's more likely the Expose event has been processed by the time both the app window and its frame window become visible, especially if there's also a compositor running.)

**Comment by brianbuccola** [comment]
Thanks, both, for the suggestions. I was just about to test them out, when I logged into xmonad and discovered that the problem is gone! I can't reproduce it anymore. I'm guessing that something got upgraded in the last few months (most recently, PyQt5) and somehow fixed the issue.

Interestingly, when I switch between workspaces, I still do *very briefly* see a border that then quickly disappears (when there's only one window) -- obviously the effect of `smartBorders`. I had thought this might be related to the original issue, but I guess not.
