### ISSUE TITLE
Black Screen during sharing on ZOOM

### ISSUE THREAD

**Issue by roper79** [xmonad/xmonad#195]
This issue seems to apply to XMonad, too:

https://www.reddit.com/r/i3wm/comments/apvq2x/zoomus_screen_sharing_black_screen_occasionally
https://github.com/i3/i3/issues/3490

**Comment by geekosaur** [comment]
This doesn't make a lot of sense. Unless Zoomus is expecting i3wm or xmonad to be "clever" and redirect drawing like a compositor does, in which case it would work if you were running a compositor like compton (neither xmonad nor i3 does compositing; gnome, kde plasma, etc. do).

Alternately maybe they're getting windows separately instead of tracking from the (virtual) root (this is arguable, especially if also handling direct rendering or video) and then thrown off by either no frame windows (xmonad) or frame the same size as the actual window and getting the z-order wrong (i3).

**Comment by roper79** [comment]
Thanks a lot for your prompt response and analysis, @geekosaur! Unfortunately, I am no expert in this, just an unhappy user. What do you suggest can be effectively done? Should I report to Zoom developers instead?

**Comment by geekosaur** [comment]
Given two different window managers, both minimalist, it's more likely to be something they're doing — and these days, highly likely they assume everyone renders to offscreen pixmaps for a compositor or etc. We'd have to know what this screen sharing program is doing in order to figure out what it should be doing or possiby what we might be able to do to help it along (for example, maybe doing something like the old LG3D hack for Java would help it to expect traditional rather than GNOME/let's-pretend-X11-is-Wayland-and-ignore-most-of-ICCCM. (DOn't even get me started. I really hope someone will fork X11 out from Red Hat and keep it going; I'm still not convinced their Wayland devs know what they're doing, and someone needs to be competing and pushing them to fix their bugs, if nothing else.)

**Comment by asr** [comment]
I also had a similar problem when sharing my display on Microsoft Teams. I fixed the problem using [this](https://docs.microsoft.com/en-us/answers/questions/42095/sharing-screen-not-working-anymore-bug.html) advice.

**Comment by PandeCode** [comment]
Thank you @geekosaur, I was able to fix this by killing my compositor ```kill -9 $(pidof picom)```.
The only issue from here was I couldn't use my compositor when in meetings but I just turn it on again after.

**Comment by slotThe** [comment]
Indeed, this does not seem xmonad related, so closing

**Comment by nabajour** [comment]
I also encountered the issue with the background being darkened in zoom screen sharing. In my case, it was due to compton compositor setting shadows on the full screen.

For Compton, you can add this to your `compton.conf`:

`
shadow-exclude = ["name = 'cpt_frame_window'" ];
`

Hope this helps anyone stumbling on this using Compton.

**Comment by Enayaaa** [comment]
same issue here, adding @nabajour 's fix didn't do it for me using picom. The exact name for the border around the screen by zoom was different for me. Following works for me: `shadow-exclude = [ "name = 'cpt_frame_xcb_window'" ];`

**Comment by jserpapinto** [comment]
This one solved it for me: https://github.com/xmonad/xmonad/issues/195#issuecomment-971395042

> `kill -9 $(pidof picom)`
