### ISSUE TITLE
Multithreading support for xmonad

### ISSUE THREAD

**Issue by poscat0x04** [xmonad/xmonad#205]
### Problem Description

I found out that all `X ()`s are blocking operations right now. I wonder is it possible to add multithreading support for xmonad with something like `forkX`.
My motivation is that I want to implement a server that listens for commands and performs `X ()` operations (in a loop) so that I can use gestures to switch workspaces.

### Configuration File

Here the code for my server:

```haskell
{-# LANGUAGE MultiWayIf #-}
-- | gesture control server using TCP

module Gestures where

import           Control.Concurrent
import           Control.Monad          (forever)
import           Network.Socket
import           System.IO
import           XMonad
import           XMonad.Actions.CycleWS

type Handler = Handle -> X ()
type Port = Int

listener :: Port -> Handler -> X ()
listener p handler = forever $ do
  let hints = defaultHints { addrFlags = [AI_NUMERICHOST, AI_NUMERICSERV], addrSocketType = Stream }
  handle <- liftIO $ do
    addr:_ <- getAddrInfo (Just hints) (Just "127.0.0.1") (Just $ show p)
    sock <- socket (addrFamily addr) (addrSocketType addr) (addrProtocol addr)
    bind sock (addrAddress addr)
    listen sock 1
    (s, _) <- accept sock
    socketToHandle s ReadWriteMode
  handler handle


handleWSCycleReq :: Handle -> X ()
handleWSCycleReq h = do
  s <- liftIO $ do
    hSetBuffering h LineBuffering
    s <- hGetLine h
    hClose h
    return s
  if | s == "prevWS" -> prevWS
     | s == "nextWS" -> nextWS
     | otherwise     -> return ()
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
An alternative might be to enable EWMH support in xmonad (which you are probably already doing anyway as many apps don't work well without it) and then use wmctrl.

**Comment by portnov** [comment]
Instead of making custom network protocol byte-by-byte, consider using one of well-known protocols — DBus, for example.

**Comment by poscat0x04** [comment]
@portnov It still blocks, right?

**Comment by portnov** [comment]
You can
1. Have some kind of shared state — Chan or MVar, or whatever
2. Have a separate thread with DBus server. I don't remember exactly, maybe by default DBus callbacks will execute in separate threads.. doesn't actually matter. In DBus callbacks, you update that shared state.
3. In XMonad functions, you use that shared state to make needed behavior.

in fact, there is no need for the "true" concurrency: no one is going to send different commands to xmonad from different threads at exactly the same time. So all the question  is to make the sequence correct, that's may be done by standard MVar / Chan / STM primitives.

**Comment by portnov** [comment]
The same can be done with "manual" network protocol, or with any other RPC protocol.

**Comment by poscat0x04** [comment]
But that takeMVar or readTChan is gonna block.

**Comment by portnov** [comment]
You can design it to never actually lock. For example, with takeMVar, it will no actually lock, if you are always having some value inside that MVar.

**Comment by liskin** [comment]
You can also just use https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-ServerMode.html. But again, for what you need, just use wmctrl and you're done in 5 minutes max.

**Comment by poscat0x04** [comment]
@liskin That did it for me.

**Comment by poscat0x04** [comment]
So xmonad-contrib actually uses some form of async request handling

**Comment by liskin** [comment]
wmctrl and XMonad.Hooks.ServerMode both use X events for communication, which is the most natural way to do async in xmonad, as it doesn't require an extra communication channel, X is already there. If you need something a bit more robust, like DBus, with methods, types, etc., you'll need to write a lot of code yourself and possibly deal with multithreading/blocking. Not sure if it's worth it. X.H.ServerMode should be enough for most stuff, albeit a bit hacky.

**Comment by geekosaur** [comment]
Redesigning xmonad's core to accept events from multiple sources would be painful and probably a breaking change, and redesigning to not assume a single thread or to use critical regions / locking or blocking in places even more so. It's been considered, but would require a complete redesign and many configs wouldn't be compatible with the result. You'd be better off writing a new window manager from scratch without xmonad's assumptions that all events come via a single-threaded libX11 connection.

Note also that X11 is inherently single threaded, even with xcb, because every thread would need its own server connection or there would be no way to (a) route incoming messages to the right thread (the X server has no idea about threads in clients) or (b) prevent messages sent from multiple threads from being interleaved. libX11 and xcb have thread locks to ensure only one thread can "hold" the connection at any given time, and even with that it's slow and doesn't work well, so most multithreaded X11 interfaces relay messages to/from the main thread which holds the server connection (see for example python's and haskell's gtk wrappers).

Changing xmonad to still be single threaded but support additional input channels (e.g. filehandle or DBus connection) would be possible and less breaking, but still require significant replumbing of the core plus new XConfig hooks which might break compatibility. And might affect compatibility with config that already use DBus (for example, mine does so as part of logHook to send `DynamicLog` data to a DBus-connected widget).

**Comment by portnov** [comment]
```haskell
main :: IO ()
main = do
  mvar <- newMVar def -- some shared state
  forkIO $ networkServer mvar
  xmonad $ def {handleEventHook = myHook mvar}

myHook mvar event = do
  -- handle event depending on contents of mvar
```

what problems may such approach have?

**Comment by poscat0x04** [comment]
@geekosaur @liskin Thanks for the clarification! I think I shall close this issue now.

**Comment by poscat0x04** [comment]
@portnov Sorry, I'm not very familiar with X events. I don't really know what event hooks do but thanks anyways.
