### ISSUE TITLE
Notification windows not being placed on top of floating windows

### ISSUE THREAD

**Issue by tsipinakis** [xmonad/xmonad#208]
Disclaimer: I'm not an xmonad user, this is the a forward of dunst-project/dunst#678, accurate steps to reproduce the issue are included in that issue, it works with the default config.

This issue seems similar, but not quite the same as #89.

### Problem Description

See dunst-project/dunst#678.

On the dunst side we call `XRaiseWindow` on `CreateNotify` events of non-override-redirect windows. I tried to make that a bit more aggressive so it raises on `VisibilityNotify`'s as well but all that does is it makes dunst and xmonad fight over who'll be on top.

### Configuration File

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
Out of the box, xmonad only supports ICCCM so such windows must use ICCCM `override_redirect`. dunst is apparently demanding EWMH support.

Additionally, you'd need some extra configuration with `EwmhDesktops` because currently it doesn't support raising such windows by itself. This is arguably a bug and there may already be a bug open for it. The support is there but must be manually configured to `doIgnore` windows with the EWMH notification window property.

**Comment by tsipinakis** [comment]
> Out of the box, xmonad only supports ICCCM so such windows must use ICCCM override_redirect. dunst is apparently demanding EWMH support.

We [do set](https://github.com/dunst-project/dunst/blob/master/src/x11/x.c#L641-L666) the `override_redirect` attribute and use the `CWOverrideRedirect` mask, is there something I'm missing here?

**Comment by geekosaur** [comment]
Interesting. Getting into a fight with xmonad over the window implies that somehow it is getting managed, but `override_redirect` should prevent that. Does a `manageHook` including

`isInProperty "_NET_WM_WINDOW_TYPE" "_NET_WM_WINDOW_TYPE_NOTIFICATION" --> doIgnore`

prevent it? (I am running xmonad under Mate and am poorly positioned to set up test environments currently.)

Note that above code requires `XMonad.Hooks.ManageHelpers` be imported from xmonad-contrib.

**Comment by tsipinakis** [comment]
I don't know any haskell so I'm unsure on how to write that in the config.

@Rufflewind could you try this out and help debug this?

**Comment by Rufflewind** [comment]
I did:

```hs
⋮
import XMonad.Hooks.ManageHelpers

main =
  xmonad (def {
    manageHook = isInProperty "_NET_WM_WINDOW_TYPE" "_NET_WM_WINDOW_TYPE_NOTIFICATION" --> doIgnore
  })
```

It had no effect AFAICT.  The bug still occurs when I resize floating windows.

**Comment by tsipinakis** [comment]
So I did some digging, and it looks like the root cause is Xmonad is calling `raiseWindow` on every move tick, dunst by default only raises when a new window is created above it, so it ends up at the bottom of the stack.
In the same way, when I patched dunsts code to also raise on `ConfigureNotify`'s, dunst and xmonad fight because both try to raise their window at the same time, leading to unpredictable results.

The following (bad/example) patch fixes xmonad for the 'move window' case at least (EDIT: while most likely breaking other things, _please do not use this as it has been barely tested :)_ )
```patch
diff --git a/src/XMonad/Operations.hs b/src/XMonad/Operations.hs
index 2845a6e..1e11476 100644
--- a/src/XMonad/Operations.hs
+++ b/src/XMonad/Operations.hs
@@ -626,7 +626,6 @@ mouseDrag f done = do
 -- | drag the window under the cursor with the mouse while it is dragged
 mouseMoveWindow :: Window -> X ()
 mouseMoveWindow w = whenX (isClient w) $ withDisplay $ \d -> do
-    io $ raiseWindow d w
     wa <- io $ getWindowAttributes d w
     (_, _, _, ox', oy', _, _, _) <- io $ queryPointer d w
     let ox = fromIntegral ox'
```

The best way to solve this would probably be on xmonads side to keep accounting of the window stack and only raise windows when necessary.

**Comment by tsipinakis** [comment]
I'm not sure if this is a relevant design decision to avoid these types of issues but it looks like i3, [manually manages the stack order](https://github.com/i3/i3/blob/1f0c628cde40cf87371481041b7197344e0417c6/src/x.c#L1215-L1224) and thus avoids using `raiseWindow`.

**Comment by liskin** [comment]
> root cause is Xmonad is calling `raiseWindow` on every move tick

I'm not seeing that behaviour here: the raiseWindow in mouseMoveWindow is only called once. But since xmonad also [manually manages the stack order](https://github.com/xmonad/xmonad/blob/a90558c07e3108ec2304cac40e5d66f74f52b803/src/XMonad/Operations.hs#L152), on every move tick we `XRestackWindows` which (according to its manpage) keeps the topmost window's stacking order intact and puts all other windows directly below, so this results in other windows obscuring dunst as well (and that's what I can reproduce here).

> In the same way, when I patched dunsts code to also raise on ConfigureNotify's, dunst and xmonad fight because both try to raise their window at the same time, leading to unpredictable results.

But this is really weird. If you really did raise the dunst window above the topmost xmonad-managed window, XRestackWindows shouldn't put anything above dunst, and XRaiseWindow isn't being called while moving (I verified this by attaching ltrace to xmonad).

Anyway, I think the `raiseWindow` may actually be dropped from `mouseMoveWindow` as it shouldn't be necessary since 4565e2c90ef522d23d3. Before that commit (and it's a commit that's been there for a while), xmonad wouldn't update its state while dragging and would only move the window using `XMoveWindow` directly, so the `XRaiseWindow` was probably necessary to ensure the window isn't obscured while dragging. After this commit, xmonad does update its state and it does sync that state with X (the `float` call invokes `windows`), including restacking, so this `XRaiseWindow` shouldn't be necessary any more.

I'll probably try dropping the `raiseWindow` call and running with that for a while, seeing if anything breaks, but I'd also want to understand that fighting between xmonad and dunst, as that doesn't fit my understanding of how xmonad works.

(Note: sorry for the late reply, xmonad doesn't have very many active maintainers, and I joined only recently. Last week I switched to dunst so that makes this a problem that directly affects me.)

**Comment by liskin** [comment]
I opened https://github.com/xmonad/xmonad/pull/275 and https://github.com/xmonad/xmonad-contrib/pull/470 as I think dropping the `raiseWindow` is really the correct fix here.

**Comment by liskin** [comment]
> > In the same way, when I patched dunsts code to also raise on ConfigureNotify's, dunst and xmonad fight because both try to raise their window at the same time, leading to unpredictable results.
> 
> But this is really weird. If you really did raise the dunst window above the topmost xmonad-managed window, XRestackWindows shouldn't put anything above dunst, and XRaiseWindow isn't being called while moving (I verified this by attaching ltrace to xmonad).

I think I now understand what was going on: xmonad raises the floating window being moved, and then calls XRestackWindows shortly after. If dunst manages to re-raise itself before xmonad gets to calling XRestackWindows, dunst "wins" and stays on top, otherwise it gets obscured by all the windows.

I originally interpreted "fight" as in continuously trying to change the stacking order resulting in flicker and CPU usage, but now it's clear to me that you just meant a one-shot race condition with an unpredicable result.
