### ISSUE TITLE
Custom modMasks?

### ISSUE THREAD

**Issue by rssoc** [xmonad/xmonad#227]
Is it possible to define a custom modMask like ```(controlMask .|. xK_t)``` for example?
Using Control or Alt interferes with Emacs, and the Windows key is in a very awkward position on my keyboard.

**Comment by geekosaur** [comment]
Not that way. You can use the xmodmap command to remap one of the 5
user modifiers, or figure out Xkb to define new ones (I don't
recommend this, Xkb is poorly documented and the relationship to
modifier bits is not specified).

This said, putting a key like 't' on a modifier effectively removes
its normal use, so you don't want to do that. You could put everything
in xmonad on a Submap activated by the 't' key, but this would be a
fair amount of work because you'd have to disable the normal
keybindings and then reproduce them in the Submap. xmonad's not really
set up for that situation. Xkb can handle it but as above is not well
documented or easy to work with.

-- 
brandon s allbery kf8nh
allbery.b@gmail.com

**Comment by rssoc** [comment]
Understood. I was just wondering if I had missed something in the documentation that would have allowed me to do this. Now that I think about it, it wouldn't have worked anyways because it would have required me to hold down all of the keys at once, as XMonad's modkey does not enter any special 'command mode' as it does in stumpwm or ratpoision.
