### ISSUE TITLE
swapUp, swapDown rotates stack when wrapping

### ISSUE THREAD

**Issue by ivanbrennan** [xmonad/xmonad#234]
### Problem Description

When `swapUp`/`swapDown` wrap around the top/bottom of the stack, they rotate the entire stack rather than swapping position with their (wrapped) neighbor. For example, with focus on the master (_A_),
```
┌─────┬─────┐           ┌─────┬─────┐
│     │  B  │           │     │  C  │
│ *A* ├─────┤ swapUp -> │  B  ├─────┤
│     │  C  │           │     │ *A* │
└─────┴─────┘           └─────┴─────┘
```
Since the non-wrapping case swaps position with the neighbor and leaves all other windows in place, I expected the wrapping case to swap _A_ and _C_,
```
┌─────┬─────┐           ┌─────┬─────┐
│     │  B  │           │     │  B  │
│ *A* ├─────┤ swapUp -> │  C  ├─────┤
│     │  C  │           │     │ *A* │
└─────┴─────┘           └─────┴─────┘
```
leaving _B_ in place.

It's easy enough to fix, but I wonder if it's a bug or the intended behavior. A [comment](https://github.com/xmonad/xmonad/blob/0db71d552a3c3779558781c8b9e654fbbe39d7e5/src/XMonad/StackSet.hs#L340-L342) in `XMonad.StackSet` mentions,
> ... the wrapping model should 'cycle' on the current stack.

Perhaps this means something other than what I expected.

A potential fix looks like:
```diff
diff --git a/src/XMonad/StackSet.hs b/src/XMonad/StackSet.hs
index d117b4a..d57ac3b 100644
--- a/src/XMonad/StackSet.hs
+++ b/src/XMonad/StackSet.hs
@@ -357,7 +357,9 @@ focusDown'                   = reverseStack . focusUp' . reverseStack

 swapUp' :: Stack a -> Stack a
 swapUp'  (Stack t (l:ls) rs) = Stack t ls (l:rs)
-swapUp'  (Stack t []     rs) = Stack t (reverse rs) []
+swapUp'  (Stack t []     rs) = case reverse rs of
+    (r:rs') -> Stack t (rs' ++ [r]) []
+    []      -> Stack t []           []

 -- | reverse a stack: up becomes down and down becomes up.
 reverseStack :: Stack a -> Stack a
```
I'm happy to create a PR, but since this is a piece of core functionality, I wanted to check first.

### Configuration File

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
On Mon, Sep 07 2020 08:19, Ivan wrote:
> ... the wrapping model should 'cycle' on the current stack.

This is the important bit.  Essentially, it's nice if these kinds of
operations have order `n`, where `n` is the number of open windows;
meaning that if we apply the operation `n` times, we end up back where
we started.  There are even two properties in `tests/Properties/Swap.hs`
to explicitly test this.  If we take your operation

    ┌─────┬─────┐       ┌─────┬─────┐
    │     │  B  │       │     │  B  │
    │ *A* ├─────┤  -->  │  C  ├─────┤
    │     │  C  │       │     │ *A* │
    └─────┴─────┘       └─────┴─────┘

and apply that three times (such that A is in the master pane again), we
end up with

    ┌─────┬─────┐
    │     │  C  │
    │ *A* ├─────┤
    │     │  B  │
    └─────┴─────┘

which is not what we started with!

**Comment by ivanbrennan** [comment]
Very interesting, thanks! @slotThe Can you elaborate on "it's nice"? Do you mean it's more intuitive to the user, or does it have important implications for functions that build on top of this operation?

It seems my operation has order `(n - 1) * n`.

Regardless, thanks for clearing up the intent. Maybe I'll submit a PR to xmonad-contrib providing a new function, `siftUp`, with the behavior I described.

**Comment by slotThe** [comment]
On Mon, Sep 07 2020 09:40, Ivan wrote:
> Can you elaborate on "it's nice"?

It's a good question.  I've thought about this a bit and there's nothing
inherent to a zipper (at least those in Huet's original paper) that says
these kinds of operations have to be cyclic.

> It seems my operation has order `(n - 1) * n`.

Indeed!  I guess there's something to be said about it being more
elegant to have the shortest possible cycle here; though that's just my
inner mathematician breaking free I think.

> Do you mean it's more intuitive to the user, or does it have important
> implications for functions that build on top of this operation?

Well, it's clearly not more intuitive to _all_ users, or you wouldn't
have opened this issue :P

Reading your first post again we do seem to have a very different model
for the operations.  You write

> When swapUp/swapDown wrap around the top/bottom of the stack, they
> rotate the entire stack rather than swapping position with their
> (wrapped) neighbor.

For me, the wrapping case is exactly what I expect to happen, because
I've always thought of the stack as an inherently cyclic thing.  This
means that `swapUp` is basically just a skewed `focusUp`; instead of
moving just the focus around this circular structure, you drag the
currently focused window with you.  This way the wrapping case is
exactly what also happens with `focusUp`.  I sadly don't know whether
that was my initial mental model of the stack or a rationalization
after-the-fact, due to how things behaved.
