### ISSUE TITLE
scratchpadManageHook broken with urxvt with tabbedex extension.

### ISSUE THREAD

**Issue by thblt** [xmonad/xmonad#24]
I use the Scratchpad extension with urxvt and a custom `scratchpadManageHook` (using `RationalRect 0.1 0.1 0.8 0.8`). This should (and does) put the terminal in a large centered rectangle, but when urxvt's [`tabbedex`](https://github.com/shaggytwodope/tabbedex-urxvt) perl extension is enabled, the scratchpad terminal appears instead in a small window somewhere on the top left of the screen. Disabling the extension in `.Xresources` fixes the bug, reactivating it reintroduces it.

I'm on ArchLinux with xmonad 0.12 and urxvt 9.22. Relevant parts of [my xmonad.hs](https://github.com/thblt/DotFiles/blob/master/.xmonad/xmonad.hs) include:

``` hs
…
myKeys :: XConfig Layout -> M.Map (KeyMask, KeySym) (X ())
myKeys conf@XConfig {XMonad.modMask = modMask} = M.fromList $
  [
…
  , ((modMask, xK_s ), scratchpadSpawnActionTerminal $ terminal conf)
]
…

main :: IO ()
main = do
  …
  xmonad def
    {
      …
      terminal = "urxvt"
    , manageHook = composeAll 
      [
        className =? "Gloobus-preview" --> doFloat
      , scratchpadManageHook $ XSS.RationalRect 0.1 0.1 0.8 0.8
      ]
    }
```

This issue doesn't appear with the standard `tabbed`

**Comment by thblt** [comment]
I believe this issue belongs in fact in xmonad-contrib. I'm closing it here.

**Comment by geekosaur** [comment]
I am actually considering whether we want these to be separate; I think the separation between xmonad and contrib just confuses most people. Unfortunately, github has no concept of projects divided up for administrative rather than technical reasons, so it would not handle associating pull requests with issues properly if we just used the xmonad issue tracker for both xmonad and contrib. :(
