### ISSUE TITLE
Reliable PID -> window should be now possible: XResQueryClientIds

### ISSUE THREAD

**Issue by deepfire** [xmonad/xmonad#27]
The `XResQueryClientIds` call introduced by XRes 1.2 should allow reliable window<->pid tracking.

Finally, we'll have reliable window <-> workspace.

http://www.x.org/releases/X11R7.7/doc/resourceproto/resproto.txt

**Comment by deepfire** [comment]
Alternatively, `XCreateWindow` should be abuseable via `LD_PRELOAD` to set up `_NET_WM_PID`:

  http://www.mail-archive.com/devel@xfree86.org/msg05806.html

**Comment by geekosaur** [comment]
On Sat, Feb 27, 2016 at 10:39 AM, Kosyrev Serge notifications@github.com
wrote:

> Finally, we'll have reliable window <-> workspace.

Until you open your second Chrome or Firefox or gnome-terminal window and
it gets moved to the same workspace as the first because it has the same
pid.
Or someone wonders why matching that second open didn't work since the pid
of the window isn't that of the launcher.
Or it forks.

Sound familiar? You still have the _same_ problems as currently.

This does not actually solve anything. You need to be able to pass a unique
token through from the launcher to the window that opens, and there is _no_
way to do that automatically and transparently in all cases. The closest
you'll get is an LD_PRELOAD to load a window porperty from an environment
variable... that will be ignored by any security-aware process, and will
_still_ do the wrong thing with factories since all windows are owned by
the same process and the mechanism that sends an open-new-window to the
backend still won't know to communicate this token to it.

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by deepfire** [comment]
> Until you open your second Chrome or Firefox or gnome-terminal window
> and it gets moved to the same workspace as the first because it has the same pid.

..which is exactly fair game, because you have asked for it!  Remember that currently, you cannot even ask for it, even if that is what you want.

> Or someone wonders why matching that second open didn't work since the pid of
> the window isn't that of the launcher.

..it is merely a tool.  That it doesn't give you all you might want doesn't mean it is not an improvement.

> Or it forks.

Now this has a more-or-less obvious solution that would work in a vast majority of cases -- just trace the parent-child relationship.

> This does not actually solve anything.

I have absolutely no idea why you have came to this conclusion.

**Comment by geekosaur** [comment]
On Sat, Feb 27, 2016 at 3:24 PM, Kosyrev Serge notifications@github.com
wrote:

> This does not actually solve anything.
> 
> I have absolutely no idea why you have came to this conclusion.
> 
> The point that you appear to have decided to ignore is that the failure
> modes here are _identical_ to the failure modes you get with the existing
> mechanism. The _only_ thing you gain here is being able to work with the
> tiny minority of programs that do not set _NET_WM_PID at all. Every other
> case is 100% identical to what you currently get. What, then. is the point?

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by deepfire** [comment]
Anything Tk-based (git gui, gitk, for example) doesn't set `_NET_WM_PID`.

**Comment by deepfire** [comment]
Ok, I have a prototype that tracks forks.  Involves `unsafePerformIO` to get to `/proc/${pid}/stat` to build the parent PID chain.

**Comment by geekosaur** [comment]
On Sat, Feb 27, 2016 at 8:06 PM, Kosyrev Serge notifications@github.com
wrote:

> Ok, I have a prototype that tracks forks. Involves unsafePerformIO to get
> to /proc/${pid}/stat to build the parent PID chain.
> 
> ...which will be rejected because (a) unsafePerformIO (b) xmonad is not
> Linux-specific, as much as Linux users would like to believe that they are
> the only people that ever matter.

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by deepfire** [comment]
@geekosaur, the specificity can be worked around, most definitely, it's not a problem -- the non-Linux cases will merely continue to suffer from imprecise parent/child relationship tracking.

**Comment by deepfire** [comment]
The `unsafePerformIO` bit is fairly contained as well:

```
getPPIDOf :: ProcessID -> Maybe ProcessID
getPPIDOf pid =
    case unsafePerformIO . tryJust (guard . isDoesNotExistError) . readFile . printf "/proc/%d/stat" $ toInteger pid of
      Left _         -> Nothing
      Right contents -> Just $ fromIntegral (read ((words . head $ lines contents ) !! 3) :: Int)
```

**Comment by deepfire** [comment]
Yay, I've made the `LD_PRELOAD` trick work for Tk windows!

Combined with pid chain tracking and as long as the command doesn't break the parent/child relationship (like, f.e. how `nohup` does), I've got `spawnOn` work for all of my applications.

For this brief moment I'm probably the happiest person on the planet!

**Comment by deepfire** [comment]
https://github.com/deepfire/ld-preload-xcreatewindow-net-wm-pid for making `_NET_WM_PID` reliable.

**Comment by pjones** [comment]
Closing issue in favor of PR xmonad/xmonad-contrib#44
