### ISSUE TITLE
Does not read xmonad.hs

### ISSUE THREAD

**Issue by klmanion** [xmonad/xmonad#270]
### Problem/Solution
xmonad, upon compilation, produces ~/.xmonad/xmonad, yet `xmonad --recompile` emits the line: XMonad is recompiling and replacing itself another XMonad process because the current process is called 'xmonad' but the compiled configuration should be called "xmonad-x86_64-freebsd".

Using `cp ~/.xmonad/xmonad ~/.xmonad/xmonad-x86_64-freebsd` xmonad starts up configured by the xmonad.hs.

Now, this makes the recompilation by META-q impossible, and has to be done everytime.

running `xmonad` works, it is not necessary to explicitly invoke xmonad-x86_64-freebsd.

Thank you.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by klmanion** [comment]
Sorry, it's necessary to run `ghc --make xmonad.hs` for this to work.

**Comment by slotThe** [comment]
On Wed, Jan 27 2021 17:44, Kurt L. Manion wrote:
> ### Problem/Solution
> xmonad, upon compilation, produces ~/.xmonad/xmonad, yet `xmonad
> --recompile` emits the line: XMonad is recompiling and replacing
> itself another XMonad process because the current process is called
> 'xmonad' but the compiled configuration should be called
> "xmonad-x86_64-freebsd".

This is the correct behaviour, you shouldn't have to do anything else
really; just wait until xmonad has recompiled and created the
`xmonad-ARCH' binary in your xmonad directory and has restarted itself.

I'm not sure I follow where your problem is here.  You don't have to do
any renaming yourself, all of this is taken care of you by the
`recompile' function.

**Comment by geekosaur** [comment]
I wonder if this is again just assuming the default compile is `ghc
xmonad.hs` when in fact the default compile adds multiple ghc options.

**Comment by geekosaur** [comment]
Only semi-relatedly, `--make` has been obsolete since ghc 6.12 (it's the
default now) and should probably go away.

**Comment by liskin** [comment]
Is there a build script (`~/.xmonad/build`) involved here? I mentioned it yesterday on IRC but it probably went unnoticed. As @slotThe said in https://github.com/xmonad/xmonad/issues/270#issuecomment-768885797, xmonad will never ever put the built binary to `~/.xmonad/xmonad` itself. Something else must be going on. And if this is your build script, then your build script is at fault, and you should really be showing us what you have in there otherwise we can't help you.

So assuming you have a build script that just does `ghc --make xmonad.hs`, that's not correct. I'm not sure if this is documented anywhere (and I'm sure https://github.com/xmonad/xmonad/blob/master/CONFIG is just plain wrong about this), but the build script is invoked with the expected output filename as its first argument, so `ghc -o $1 xmonad.hs` might work in the build script.

But yeah, the documentation is bad. :-/

**Comment by klmanion** [comment]
> Is there a build script (`~/.xmonad/build`) involved here? I mentioned it yesterday on IRC but it probably went unnoticed. As @slotThe said in [#270 (comment)](https://github.com/xmonad/xmonad/issues/270#issuecomment-768885797), xmonad will never ever put the built binary to `~/.xmonad/xmonad` itself. Something else must be going on. And if this is your build script, then your build script is at fault, and you should really be showing us what you have in there otherwise we can't help you.
> 
> So assuming you have a build script that just does `ghc --make xmonad.hs`, that's not correct. I'm not sure if this is documented anywhere (and I'm sure https://github.com/xmonad/xmonad/blob/master/CONFIG is just plain wrong about this), but the build script is invoked with the expected output filename as its first argument, so `ghc -o $1 xmonad.hs` might work in the build script.
> 
> But yeah, the documentation is bad. :-/

[build.txt](https://github.com/xmonad/xmonad/files/5902146/build.txt)

So I never touched build.  It was generated for me.  (This is simply called build on my system, I had to give it this extension so I could upload it.)

> This is the correct behaviour, you shouldn't have to do anything else really; just wait until xmonad has recompiled and created the \`xmonad-ARCH' binary in your xmonad directory and has restarted itself. I'm not sure I follow where your problem is here. You don't have to do any renaming yourself, all of this is taken care of you by the `recompile' function.

The issue is that the xmonad-ARCH binary is not being produced.

Sorry for the late response--work consumed me recently.

**Comment by liskin** [comment]
It seems the build script does try to move the binary to the correct (`$1`) spot, but for some reason fails to do so. I'm guessing cabal has changed a lot since this last worked.

Can you please report this issue to your distribution or whatever generated the `build` script?

**Comment by klmanion** [comment]
> It seems the build script does try to move the binary to the correct (`$1`) spot, but for some reason fails to do so. I'm guessing cabal has changed a lot since this last worked.
> 
> Can you please report this issue to your distribution or whatever generated the `build` script?

So I deinstalled and reinstalled xmonad by means of the ports tree.  The `build` script shown in my previous comment is the same as it occurs in `/usr/local/share/examples/xmonad/build`.  I had to `cp` it this time; not sure how it got there the first time around.

I still don't understand though why you think the problem is with the build script.  As far as I can tell it's trying to make `xmonad-config`, and I don't know what this has to do with the final executable not being called `xmonad-ARCH`.

**Comment by klmanion** [comment]
Okay—so in this fresh install I did not put the `build` script found in the examples in `~/.xmonad`.  It used the ghc build script (I believe that's what it said) and it produced the `xmonad-ARCH` binary.

**Comment by liskin** [comment]
> I still don't understand though why you think the problem is with the build script.

It's simple, really. The build script is supposed to generate a file named `xmonad-something-something`, and this filename is passed to the script as the first argument (`$1`). Your build script failed to generate such a file. It may have generated `xmonad-config` or `xmonad` or `ihavenodamnideawhat`, but it didn't generate what it was told to generate, and that's what the problem is.

Now even if you eventually got this fixed by removing the script, please do report this issue to whoever maintains the `/usr/local/share/examples/xmonad/build` in your distribution because it clearly doesn't work, and debugging this issue wasted a lot of time. Then please do link the issue here so that when the next person comes with a similar problem, we can refer them to your report. Thank you.

**Comment by klmanion** [comment]
> > I still don't understand though why you think the problem is with the build script.
> 
> It's simple, really. The build script is supposed to generate a file named `xmonad-something-something`, and this filename is passed to the script as the first argument (`$1`). Your build script failed to generate such a file. It may have generated `xmonad-config` or `xmonad` or `ihavenodamnideawhat`, but it didn't generate what it was told to generate, and that's what the problem is.
> 
> Now even if you eventually got this fixed by removing the script, please do report this issue to whoever maintains the `/usr/local/share/examples/xmonad/build` in your distribution because it clearly doesn't work, and debugging this issue wasted a lot of time. Then please do link the issue here so that when the next person comes with a similar problem, we can refer them to your report. Thank you.

Thank you for your time

The bugzilla report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253167

And, again, for anybody running into this issue: Simply delete `~/.xmonad/build`; the ghc build script that xmonad falls back on will successfully emit `xmonad-ARCH`.
