### ISSUE TITLE
Signal (Chromium app) to workspace

### ISSUE THREAD

**Issue by sebastianv89** [xmonad/xmonad#31]
I just installed Signal, which is a chromium app. When I launch it, I want the window to go to my fourth workspace. So I added the following line to myManageHook:

``` haskell
, title =? "Signal" --> doShift "4:chat"
```

But the app just launches in my current workspace.
I checked the window with xprop, which returns:

```
WM_NAME(UTF8_STRING) = "Signal"
_NET_WM_NAME(UTF8_STRING) = "Signal"
```

Is this a bug or am I doing something wrong?

**Comment by geekosaur** [comment]
Neither, unfortunately.

Browsers can't set the window title properly until they have rendered its content, since the final title may come from an HTTP `<title>` element or from JavaScript that runs during or even after page load (the latter, for Chromium extensions). The title that window managers see for Chrome/Chromium at `ConfigureRequest` time (which is when `xmonad` runs the `manageHook`) is a default string that _all_ browser windows have initially; at extension load time this changes to a string based on the hashed name of the extension, then after the extension's initial page is rendered it changes to the final title.

http://lpaste.net/149383 is something of a hackaround that runs from the `handleEventHook` and moves the window, or does something else to it, when the final title is set. There isn't a whole lot else that can be done; browser windows are far too dynamic.
