### ISSUE TITLE
Getting library error on startup after update xmonad

### ISSUE THREAD

**Issue by mastersilvapt** [xmonad/xmonad#335]
Unable to access shared library: libhsxmonad-contrib-0.16-7l6vmvis0blffsdcn6gsxw-ghc8.10.5.so

i use "sudo pacman -U /var/cache/pacman/pkg/xmonad-0.15-149-x86_64.pkg.tar.zst" to get my old install and it works again. No lib errors.

**Comment by slotThe** [comment]
When are you getting this error, exactly?  This may or may not also be more of an Arch issue than an xmonad one (Arch's dynamic linking of Haskell packages breaks... lots of stuff all the time)

**Comment by geekosaur** [comment]
It could also be that the automatic recompile of the user config is either breaking on some incompatibility (recall that actually displaying build errors properly is only fixed in git) or simply not happening because it can't check the system libraries. "`xmonad --recompile`" in a terminal window may help.

**Comment by mastersilvapt** [comment]
After updating xmonad

> 
> 
> When are you getting this error, exactly? This may or may not also be more of an Arch issue than an xmonad one (Arch's dynamic linking of Haskell packages breaks... lots of stuff all the time)

after updating xmonad.

**Comment by mastersilvapt** [comment]
> 
> 
> It could also be that the automatic recompile of the user config is either breaking on some incompatibility (recall that actually displaying build errors properly is only fixed in git) or simply not happening because it can't check the system libraries. "`xmonad --recompile`" in a terminal window may help.

Same output.

**Comment by geekosaur** [comment]
Bleh, that sounds very wrong. But it also sounds like you need to take it up with the Arch maintainer because they did something wrong; the main `xmonad` executable should have been properly updated to use the new shared objects. (This is one reason the Haskell ecosystem doesn't build things shared like Arch does.)

**Comment by mastersilvapt** [comment]
Ok thanks.
