### ISSUE TITLE
Security issue: mate-screensaver lock screen becomes a tile

### ISSUE THREAD

**Issue by robbertkrebbers** [xmonad/xmonad#40]
I am not sure whether this is a bug in xmonad or a bug in mate-screensaver, but I am reporting it regardless because it is a serious security issue.

Using mate-screensaver 1.14.1 and xmonad 0.12, the lock screen becomes a tile. This means that you can just resize the screensaver using the mouse, and interact with running applications, thus circumventing the purpose of locking the screen.

See also https://github.com/mate-desktop/mate-screensaver/issues/96

**Comment by robbertkrebbers** [comment]
This bug no longer appears when using the last version of mate-screensaver (commit dd83748). So, it was probably a bug in mate-screensaver, and not in xmonad.

**Comment by geekosaur** [comment]
On Tue, Jul 12, 2016 at 12:04 PM, Robbert Krebbers <notifications@github.com

> wrote:
> 
> This bug no longer appears when using the last version of mate-screensaver
> (commit dd83748). So, it was probably a bug in mate-screensaver, and not in
> xmonad.

Somehow I never saw this issue. But yes, a screensaver must use
override-redirect, otherwise it is not taking full control like a
screensaver must to ensure security. If xmonad was seeing the window at
all, they weren't using override-redirect.

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net
