### ISSUE TITLE
How I can prevent applications grab window focus

### ISSUE THREAD

**Issue by unclechu** [xmonad/xmonad#45]
Some applications shows modal windows that can be annoying some times and make unexpected consequences (like gets dangerous key combos that supposed to be sent to another application). I wish I could be able to prevent windows grabbing focus, I imagine white-list of applications that can do it and any other can't. Some applications also trying to regrab the focus to modal window if main window got focused, and if autofocus by mouse turned on it can have insane results, lags and stuff. I hope we can just ignore this tries to grab focus, without back-switching hacks.

**Comment by sgf-dma** [comment]
Hi.

I think, you may try to use a module, which allows to manage focus switch: https://gist.github.com/sgf-dma/99712cbfedf278d2a6e871ac70749b48 .

It's not in xmonad-contrib for some reasons and since i (as the author) am the one to blame for this, i offer you help in setting it up: describe your situation in more details, please. Which applications particularly, and which windows you want to ignore.

**Comment by pjones** [comment]
@unclechu Have you tried the suggestion from @sgf-dma?

**Comment by unclechu** [comment]
@pjones not yet, I'll try it in near future, I let you know if it helps.

**Comment by f1u77y** [comment]
xmonad/xmonad-contrib#110

**Comment by sgf-dma** [comment]
Hm.. so much efforts were thrown into fixing focus grabs by different people. I didn't even imagine.

@pjones, then, would you be interested in my module to be in xmonad-contrib? I may try to rewrite comments into haddock format rather quickly (within one-two days, i hope). Or are there already other approaches, which you prefer? I still can't add tests that fast, but are they really required for accepting new module?

**Comment by unclechu** [comment]
@sgf-dma thanks a lot! I tried your solution and it works for me!
Here is [commit where I added it to my config](https://github.com/unclechu/xmonadrc/commit/cf9db97829bbcb714eaceebc278ac30adab0126f).

**Comment by simlu** [comment]
@unclechu That's one big pr... I honestly don't want to understand all that. Mind pointing me to the correct line that would allow me to disable automatic focus changes entirely? I hope that's just a small non-invasive change?

Thank you! L~

**Comment by sgf-dma** [comment]
Hi.

It's not a non-invasive change at least because that PR wasn't merged (it was
reverted after merge). Now it's at
https://github.com/xmonad/xmonad-contrib/pull/192 .

I've rebased it on current master now, so you may want to try to compile
xmonad with custom `xmonad-contrib`.. And then..


    import XMonad
    import XMonad.Util.EZConfig

    import XMonad.Hooks.EwmhDesktops
    import XMonad.Hooks.ManageHelpers
    import XMonad.Hooks.Focus

    main :: IO ()
    main = do
            let fh :: ManageHook
                fh = manageFocus $ composeOne
                        -- For activated windows.
                        [ liftQuery activated -?> keepWorkspace <+> keepFocus
                        -- For new windows.
                        , Just <$> switchFocus
                        ]
                xcf = ewmh $ def
                        { modMask = mod4Mask
                        , manageHook = fh <+> manageHook def
                        , logHook = activateLogHook fh <+> logHook def
                        }
                    `additionalKeys` [((mod4Mask, xK_v), focusLockOn)]
                    `additionalKeys` [((mod4Mask .|. shiftMask, xK_v), focusLockOff)]
            xmonad xcf

1.  I've enabled EWMH handling (read: window activation), because some
    programs grab input focus without window focus (well, window focus is
    preserved using X.H.Focus). With EWMH enabled, this won't happen (at least
    for me).

2.  There is a `fh :: ManageHook` defining how window focus will be moved.
    For activated window works the `liftQuery activated` line, for others
    (i.e.  new window) work the last `Just <$>` line. The order matters,
    because the `Just <$>` line will match with activated window too.

3.  There're functions: `switchFocus` and `keepFocus`, `switchWorkspace` and
    `keepWorkspace` provided by `X.H.Focus`. Combine them using `<+>` (the
    order, probably, does not matter - i don't remember, i've written this too
    long ago). Probably, some of them are excessive in example above (i don't
    remember either), but i wrote this to specify behavior explicitly.

4.  Then add this `fh` to `manageHook`, if you want to run it
    for new windows, and to `logHook`, if you want to run it for
   activated windows.

5.  Also, there is a "focus lock" feature. It'll prevent focus move completely
    (i.e. neither new nor activated window will grab focus; it's equivalent to
    `keepFocus <+> keepWorkspace` specified for new and activated windows).
    You may enable/disable it manually using keybinding.
