### ISSUE TITLE
Xmonad Freezing 

### ISSUE THREAD

**Issue by illis** [xmonad/xmonad#55]
Heya,

Seems to be a few people running ArchLinux w/ Xmonad running in a few freezing issues. The current window that you are in still works fine, but you xmonad itself becomes unresponsive (doesn't respond to shortcuts etc).  If you switch to a new tty or are currently in a terminal you can issue the following pkill command to unfreeze the xmonad session:
`pkill -CONT xmonad-x86_64-l `

Links to arch bbs with more info:
https://bbs.archlinux.org/viewtopic.php?id=216074
https://bbs.archlinux.org/viewtopic.php?id=216293

Let me know if there is any more info I can provide. 

Cheers,

**Comment by geekosaur** [comment]
The first link shows a classic xmobar configuration mistake: Run
StdinReader is in the commands, but there is no %StdinReader% in the
template so xmobar doesn't actually start the StdinReader. But xmonad is
still configured to write DynamicLog information to the pipe, and
eventually will stall because xmobar is not reading from the pipe. (ghc
currently gives us no way to detect this or prevent the stall.) Killing the
xmobar will also unstick xmonad, as will draining the pipe in some other
way (e.g. "cat /proc/$(pidof xmobar)/fd/0" in a terminal).

See
https://wiki.haskell.org/Xmonad/Frequently_asked_questions#XMonad_stops_but_the_current_window_still_responds_to_keys
for more information.

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by geekosaur** [comment]
If you really want to use xmobar without receiving `DynamicLog`
information, don't use `xmobar` or `statusBar` in xmonad to start it. Use
`spawnOnce "xmobar" in the`startupHook` instead. (See
http://hackage.haskell.org/package/xmonad-contrib-0.12/docs/XMonad-Util-SpawnOnce.html
)

On Thu, Nov 3, 2016 at 7:01 PM, Brandon Allbery allbery.b@gmail.com wrote:

> The first link shows a classic xmobar configuration mistake: Run
> StdinReader is in the commands, but there is no %StdinReader% in the
> template so xmobar doesn't actually start the StdinReader. But xmonad is
> still configured to write DynamicLog information to the pipe, and
> eventually will stall because xmobar is not reading from the pipe. (ghc
> currently gives us no way to detect this or prevent the stall.) Killing the
> xmobar will also unstick xmonad, as will draining the pipe in some other
> way (e.g. "cat /proc/$(pidof xmobar)/fd/0" in a terminal).
> 
> See https://wiki.haskell.org/Xmonad/Frequently_asked_
> questions#XMonad_stops_but_the_current_window_still_responds_to_keys for
> more information.
> 
> ## 
> 
> brandon s allbery kf8nh                               sine nomine
> associates
> allbery.b@gmail.com
> ballbery@sinenomine.net
> unix, openafs, kerberos, infrastructure, xmonad
> http://sinenomine.net

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by pjones** [comment]
@illis If your problem isn't fixed by using @geekosaur's suggestion, please reopen this issue and include your xmonad configuration.  Thanks.

**Comment by illis** [comment]
Heya, sorry about the late reply. My particular config does have the %StdInReader% in the template. I've run the same configs for a very long time without any issues.

I don't get nearly as many lockups at the moment, as I used to (nearly every 15 minutes). Now I only tend to sometimes get them after resuming from a suspend. 

What I have come down to, is that its something Thinkpad specific and I think a change in one of the kernels? has changed some way something is being reported.  I might try removing my battery stats from xmobar and see if that helps over the next couple of weeks.

**Comment by tekul** [comment]
@illis There seems to be [an issue](https://bbs.archlinux.org/viewtopic.php?id=216949) with using `dbus-launch` in your .xinitrc, which is apparently now deprecated. [My config](https://github.com/tekul/dotfiles) worked OK on Ubuntu, but after switchg to Arch I would get the freeze up a few times a day - I had several stopped ('T' status)  processes as described in that thread, including `xmonad` and `urxvtd`. I've removed the `dbus-launch` from my config and it seems OK so far.

**Comment by illis** [comment]
@tekul Thanks heaps for the tip :) I'm gonna give that a shot now, I'll report back if all is well :)

**Comment by hicolour** [comment]
I had very similar issue with freezing windows, and couldn't figure out what was the reason. On  the reddit/xmonad someone suggest that had the same issue on thinkpad and indeed it looks like this is hardware specific issue.  (In my case it was Lenovo Thinkpad T480s)

Bellow you can find my tips on how to do painless firmware update.
https://gist.github.com/hicolour/a08c1413d1bd7acb524aa043ac37cafa


I upgraded the firmware  and the issue occurs less frequently.

---

Only few type of windows are affected - mainly applications having web engine inside (qutebrowser, chrome, spotify) so it might be something related with acceleration.

**Comment by Memorytaco** [comment]
### does the problem seems like that here?(right bottom corner)
![screen](https://user-images.githubusercontent.com/30775014/67543456-07028600-f724-11e9-8188-f1eda987aec9.png)

uname output : `Linux Pixel 5.3.7-gentoo #7 SMP Mon Oct 21 19:00:46 CST 2019 x86_64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel GNU/Linux`

alacritty and chromium has been affected and i have no idea. They just don't get updated and the problem occured quite often. I have to pkill them and reopen it but same situation will appear quite soon. gvim, firefox and st seems working fine. btw, spotify will be affected also.

i use stack to build the xmonad with just eight or nine lines of configured code:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import XMonad
import XMonad.Util.EZConfig (additionalKeys)
import System.IO

main = do
  spawn "ibus-daemon -rdx"
  spawn "feh --bg-fill ~/.config/awesome/wall.jpg"
  xmonad $ def {
      terminal = "alacritty"
    , borderWidth = 2
    , modMask = mod4Mask
    , focusedBorderColor = "#ebdbb2" -- "#3ab811"
    , normalBorderColor = "#282828"
    } `additionalKeys`
    [
      ((mod4Mask, xK_d), spawn "rofi -show run")
    ]
```

and here is my xinitrc:
``` bash
QT_IM_MODULE=ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus

xrdb .Xresources
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session /home/user/.local/bin/xmonad
```

I don't know how to describe this problem, just basic information. That's really weird.

**Comment by hicolour** [comment]
This is exactly the issue I have.

I'm quite sure that issue we have is different than original issue #55

@Memorytaco it might be good idea to open new issue.

**Comment by geekosaur** [comment]
This one may be chromium and chrome requiring EWMH to be configured to work properly. It looks somewhat familiar; you might check the `xmonad-contrib` issues as well as `xmonad`.

You also didn't export the variables you set, so they aren't visible outside the shell. I'd also use `-merge` with the `xrdb` invocation. Neither of these should cause this behavior, though.

**Comment by Memorytaco** [comment]
@geekosaur  will check xmonad-contrib. btw, awesome has this problem too. i switched to xmonad intending to solve this problem.

i don't think xrdb will cause any problem because i fairly didn't set any sensible value in Xresources. I did that for gtk theme.

@hicolour After checking xmonad-contrib, i will open a new issue.

Thanks.

**Comment by hicolour** [comment]
Might be https://github.com/xmonad/xmonad-contrib/issues/227

**Comment by Memorytaco** [comment]
a light weight compositor can handle this. see [simple solution](https://github.com/xmonad/xmonad/issues/201#issue-515477499). @hicolour
