### ISSUE TITLE
Honor fixed size floating windows.

### ISSUE THREAD

**Issue by incertia** [xmonad/xmonad#80]
### Problem Description

If a window has both the minimum and maximum size set in the WM_NORMAL_HINTS property, XMonad will automatically float this window, but you can still change the window size via the hotkeys. Is there any way to enforce this property?

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

**Comment by pjones** [comment]
I'm not aware of any way to enforce this property in xmonad.  Sounds like this could be an optional module in xmonad-contrib for those that want this.

**Comment by geekosaur** [comment]
There is no way to enforce it, and technically xmonad's behavior is correct because they are explicitly hints that the window manager is permitted to ignore. Practically, I'd like xmonad to do something like changing the border color (granting this won't work if border size is 0) while resizing if you go outside the hints, but that'd take some work.

**Comment by pjones** [comment]
Closing as `wontfix`
