### ISSUE TITLE
color string does not parse expose transparency

### ISSUE THREAD

**Issue by rmanne** [xmonad/xmonad#85]
### Problem Description

While `Pixel` appears to support transparency (most significant byte), it's impossible to set it by using strings, for example in `normalBorderColor` and `focusedBorderColor`.

However, something like "#00000000" (zero alpha for transparency), fails to parse and appears to default to something where alpha is not 1 but also not 0 with the rest of the pixel being 0xffffff. In other words, the only way to get an even partially transparent border color is to make it unparsably wrong.

Could this feature be added to allow transparent borders (mostly only for normalBorderColor)?

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by pjones** [comment]
This would be neat to have.

If you have a time this should be a simple change to the source code.  If not, beg a Haskell programmer that you know ;)

**Comment by geekosaur** [comment]
This can't be done by changing parsing, since the border color has to be parseable for non-RGBA windows. You'd need to add new fields to `XConfig`/`XConf` to be used only for RGBA windows. (No, we can't make transparent borders on RGB windows. This would require exporting the desired transparency in a window property *and* modifying the compositor to honor that property.)

**Comment by rmanne** [comment]
@geekosaur  Wouldn't  this change make more sense in the X11 library? I think it would belong `allocNamedColor` (or one of the functions it uses). 

@pjones For now, I hacked myself something, but the transparency is not respected on windows that don't already have transparency set. As geekosaur said, the model might have to change, since you would need to export the desired transparency in a window property, which is not done right now.
The hack (line 440 in current xmonad repo, replacing initColor):
```Haskell
initColor :: Display -> String -> IO (Maybe Pixel)
initColor dpy ('#' : c' ) | length c' == 8 =
    fmap (\p -> p .&. 0x00ffffff .|. alpha)
      <$> initColor dpy ('#' : drop 2 c')
    where alpha = read ("0x" ++ take 2 c' ++ "000000") :: Pixel
initColor dpy c =  C.handle (\(C.SomeException _) -> return Nothing) $
    (Just . color_pixel . fst) <$> allocNamedColor dpy colormap c
    where colormap = defaultColormap dpy (defaultScreen dpy)
```

See below how urxvt (which has transparency on) respects the alpha, but chromium which doesn't, ignores the alpha.
![2017-03-14-13 45 25](https://cloud.githubusercontent.com/assets/1724749/23914527/94ea0794-08bc-11e7-9a12-c727e31d1ebf.png)
![2017-03-14-13 45 26](https://cloud.githubusercontent.com/assets/1724749/23914526/94e9895e-08bc-11e7-9174-b31ecedc70a4.png)

**Comment by geekosaur** [comment]
@rmanne, if you want to redesign all of X11 so transparency isn't an utter hack, sure. Note that the X.Org devs already tried that and "failed" (despite having *working code* from SGI!). Reworking xorg is not on the table. And if you mean the X11 binding, then no, it can't be done there, it has to be done in the server and xlib/xcb.

**Comment by rmanne** [comment]
@geekosaur ah yes, I meant the X11 binding
I was under  the assumption that it was doing the parsing, but now I see it's sending the full string into the library.
Hmm, if it can't be done there though, I wonder how one WOULD approach this problem.

**Comment by geekosaur** [comment]
You'd have to specify the transparency as an extra component that xmonad would add to the color only for RGBA windows, or a separate color spec for those. And, again, there's no way to get it to work for non-RGBA windows without having a separate communication channel of some kind with the compositor (which means the compositor has to be modified to know about it). This is because RGBA support is a horrible hack; there is literally nowhere to put the opacity data in an RGB window, you have to put it elsewhere and teach the compositor to look for it.

**Comment by pjones** [comment]
@rmanne Are you interested in working on a patch that would make this work on windows that are already RGBA?  If not I might just close this issue.

**Comment by rmanne** [comment]
@pjones imo, consistency is more important for me, and not all of my windows are rgba, so I've been just working with the solid colors. You might as well close the issue.
The code I pasted above already works for rgba windows (may be slightly buggy).
