### ISSUE TITLE
The screen didn't draw anything until I changed HDMI connection

### ISSUE THREAD

**Issue by CindyLinz** [xmonad/xmonad#92]
### Problem Description

The situation is weird... I use `xmonad` on my laptop. After I started the `xmonad` by typing `startx` in console mode, the screen became whole black and did not draw anything even if I pushed `alt-shift-enter` many times to open `xterm` several times, until I changed the HDMI connection (that is, to connect the HDMI cable if it was initially disconnected; or to disconnect it if it was initially connected). After I changed the HDMI connection, the screen suddenly refreshed correctly. I didn't try VGA or DVI connections, because I don't have these type of screens.

I've tried some versions. With `xmonad-v0.13` and `X11-1.8`, I got into this situation. With `xmonad-v0.12` and `X11-1.6.1.2`, I got into this situation with `stack lts-8.0` or later versions, and it operated normally with `stack lts-7.20` or former versions.

If you need other environment information, ask me more~

### Configuration File

```haskell
import XMonad
main = xmonad defaultConfig
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by pjones** [comment]
This is a strange one indeed.  Have you seen any errors on the console where you ran startx?  What happens if you try to restart xmonad while it's in this state of not responding?

**Comment by CindyLinz** [comment]
There was no error message.. And to restart xmonad by `alt-shift-r` didn't change anything.

It was only frozen on refreshing screen. I could still press `alt-shift-q` to close it and returned back to console. Then the console operated and displayed normally.

**Comment by pjones** [comment]
Is this a recurring issue that you can reproduce on demand?

Perhaps it would help if you dropped your configuration into [xmonad-testing](https://github.com/xmonad/xmonad-testing).  You can use stack to build there but would build off of the latest source code instead of the last release.

One of the things that comes to mind is a recent change to the X11 library.  When you had things working with `stack lts-7.20` which version of xmonad and X11 were you using?

Finally, after starting xorg and you get the black screen, switch back to another virtual console (Ctrl-Alt-F2), log in, and start an xterm:

    $ DISPLAY=:0 xterm

Switch back to xorg (Alt-F7) and see if xmonad put borders around the window.

Sorry for all the ideas and things to try.  I'm sort of shooting in the dark here.

**Comment by CindyLinz** [comment]
This problem seems disappeared..
I upgraded my system (Linux Arch distro), and I tried `xmonad-0.13` with `stack lts-8.6` and `stack lts-8.12`. Everything works fine now.
It might be a problem of the backend..~

Sorry for bothering you these days.

**Comment by pjones** [comment]
Thank you for the update.

**Comment by cdepillabout** [comment]
I ran into a problem very similar to this.  I'm in the process of moving to using a build script to build xmonad with `stack`, instead of just installing with my package manager (on Arch Linux).

I've been fighting with this problem for the last two hours or so.  As best I can tell, this was solved by doing a `rm ~/.xmonad/xmonad.hi ~/.xmonad/xmonad.o`.

Having those two files (from a previous installation of xmonad?) seemed to cause xmonad to fail to startup.  However, I didn't get any errors or anything, just a blank screen.

Here is my build script and xmonad.hs in case anyone is interested:

https://github.com/cdepillabout/docs/tree/master/dot_files/dot_xmonad

**Comment by geekosaur** [comment]
If it's those two files, this points the finger squarely at your build script (they're build artifacts from the built-in build script).

**Comment by geekosaur** [comment]
Actually, it should not even look at those files if it is using a build script, because it can't know what build artifacts exist or where they are....

@pjones?

**Comment by pjones** [comment]
I don't see how the `*.hi` or `*.o` files would come into play at all.

**Comment by cdepillabout** [comment]
> If it's those two files, this points the finger squarely at your build script (they're build artifacts from the built-in build script).

I assumed they were artifacts of calling GHC directly from the command line (as opposed to using a build tool like `cabal` or `stack`), since it usually leaves around a bunch of files like `.hi` and `.o`.  I'm guessing this is essentially what xmonad is doing when rebuilding?

In my build script, I am also calling GHC directly:
https://github.com/cdepillabout/docs/blob/master/dot_files/dot_xmonad/build#L67

My working theory is that when calling GHC directly from the build script, it reused the cached `.hi` or `.o` files (which were created from a system-installed xmonad) even when it should not have.

I should have made this clear in my original post, but I do not think this is necessarily an xmonad problem (and I don't really even think my diagnosis is correct, since GHC should ignore old `.hi` and `.o` files).  I just wanted to post a possible solution so anyone else having this problem might try it.

However, I do really appreciate the quick reponse @geekosaur and @pjones!
